<?php
/**
 * Created by PhpStorm
 * User: BanJin
 * Date: 2021/12/21
 * Time: 11:34
 */

namespace Ban\Facades;

use Illuminate\Support\Facades\Facade;

class EaseMobTest extends Facade
{

    protected static function getFacadeAccessor()
    {
        // TODO: Change the autogenerated stub
        return "easemobtest";
    }
}
